Feature/hacker news
u1timaD/webbee-hackerNews pull request #1
Opened 2024-07-28 12:46 UTC by u1timaD

https://stackblitz.com/edit/vitejs-vite-cmwtku

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +  ],
там же получение новейших, в задании, но лучше так оставь
а ещё не знаю сколько там всего можно получить, но будто бы сильно больше чем нужно

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +  ],
А ещё нет смысла эти данные хранить в сторе

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +};
это общий фетч а не фетч определенных новостей

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +}
Для стора не используй Props,, тк это не пропы

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +}));
Не корректно держать 2 стора на одном файле

2024-07-29 02:57 UTC, IvanKoigerov commented on src/utils/utils.tsx
> +};
Давай потрогаем такую библиотеку как date-fns

2024-07-29 02:57 UTC, IvanKoigerov commented on src/utils/utils.tsx
tsx некорректный формат
А ещё не круто, что тут лежат функции для совершенно разных вещей, лучше всего делить такие вещи на разные файлы

2024-07-29 02:57 UTC, IvanKoigerov commented on src/zustand/store.ts
> +  fetchAllNews: () => void;
ууу это не промис?

2024-07-29 02:57 UTC, IvanKoigerov commented on src/utils/utils.tsx
> +};
не вижу смысла в этой функции, лучше на месте чекать это значение и возвращать null  в таком случае

2024-07-29 02:57 UTC, IvanKoigerov commented on src/utils/utils.tsx
> +export const sortNewsByTime = (news: FeedItem[]) => [...news].sort((a, b) => b.time - a.time);
toSorted есть

2024-07-29 02:57 UTC, IvanKoigerov commented on src/App.css
> +  -moz-osx-font-smoothing: grayscale;
ляя а шо так много вещей описано в глобальных стилях, это некорректно, ты никогда не знаешь, где это нужно переопределить, а лишний раз себе усложнять жизнь не круто

2024-07-29 02:57 UTC, IvanKoigerov commented on src/App.css
>  }
А я разве не писал в каком-то из пров, что body нельзя стилизировать? для этого существуют отдельные контейнеры

2024-07-29 02:57 UTC, IvanKoigerov commented on src/App.css
>  }
Не на каждой странице в body тебе нужны эти стили, а где-то это приведет к переписке и тд, так что никогда так не делаем

2024-07-29 02:57 UTC, IvanKoigerov commented on src/App.tsx
>      <>
нет смысла в <>

2024-07-29 02:57 UTC, IvanKoigerov commented on src/Types/interface.ts
> +export interface Item {
Item чего

2024-07-29 02:57 UTC, IvanKoigerov commented on src/Types/interface.ts
> +export interface FeedItem {
FeedItem тут тоже непонятно к чему это именно относиться

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  padding: 20px 20px;
почему не просто padding: 20
А ещё раз тут mui, то давай использовать theme.spacing

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  cursor: pointer;
почему у бокса pointer
если ты можешь нажать на этот элемент и тут что-то произойдет, то ты должен использовать либо кнопку либо линку, некорректно для этого использовать div

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  background-color: #d9e5fe;
выноси все цвета в тему

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +    comment.comments.length !== 0 && setOpen(!open);
у тебя может быть некорректно значение в open если меняешь его ещё где-то изменение open, и тут ты можешь в моменте увидеть некорректный вызов

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +      </StyledCollapse>
unmountOnExit что этот проп делает?

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/UpdateButton/UpdateButton.tsx
> +  };
Используй if, это делает код более читабельный
Да и я бы на твоем месте лишний раз бы не делал проверку а return делал

2024-07-29 02:57 UTC, IvanKoigerov commented on src/main.tsx
> +  // </React.StrictMode>,
не правильно открывать пр, если есть в нем комментарии, а ещё мы не убираем StrictMode

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/Home/Home.styled.ts
> +export const NewsSection = styled(Box)``;
Будто бы незачем

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/Home/Home.tsx
> +  }, []);
повторяешься

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/Home/Home.tsx
> +      <NewsList>{loading ? <Loading count={10} /> : news.map((item) => <News key={item.id} {...item} />)}</NewsList>
если у тебя будут одинаковые данные, то ты заново лишний раз заререндеришь компоненты, а так как их 100, это потеря производительности 
+ у тебя каждую минуту появляется лоудер, а это не круто, у тебя в такой ситуации пользователь теряет возможность работать со страницей 

также нужно показывать все равно лоудер, когда юзер кликает на кнопку обновления, чтобы показать пользователю, что ты делаешь запрос за данными

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.styled.ts
> +  box-shadow:
тени тоже лучше всего заносить в тему

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.styled.ts
> +`;
все Typography тоже лучше всего заносить в тему

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.styled.ts
> +  gap: 6px;
какой-то очень маленький gap

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.tsx
> +  if (loading) return <Loading count={1} />;
тут та же проблема но со всеми новостями

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.tsx
> +    <>
тебе не нужны <></>

2024-07-29 02:57 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.tsx
> +          <Collapse in>{comments && <NestedComments key={id} comments={comments} />}</Collapse>
если нет комментарием, то ты рендеришь лишний раз Collapse

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/NestedComments/NestedComments.tsx
> +            }}
фу какой style

2024-07-29 02:57 UTC, IvanKoigerov commented on src/components/NestedComments/NestedComments.tsx
куча компонентов для отображение комментарием, очень усложняешь, можешь это упростить

2024-07-29 18:12 UTC, u1timaD commented on src/zustand/store.ts
> +  ],
Я когда делал, получение новеших выдавало ошибку, думал не работает, сейчас же всё приходит нормально. Переделаю на новейшие.

2024-07-29 19:04 UTC, u1timaD commented on src/main.tsx
> +  // </React.StrictMode>,
моя вина, не заметил(

2024-08-07 10:08 UTC, myaak requested changes

2024-08-07 10:08 UTC, myaak commented on src/Store/newsDetail.ts
> +        set({ loading: true });
Вообще не понял что тут происходит, у тебя забатчится эта штука и зачем тут ставить лоадинг, если ты снизу его снимаешь, в чем смысл?

2024-08-07 10:08 UTC, myaak commented on src/Store/newsDetail.ts
> +  fetchNewsDetail: async (id, load) => {
Что означает переменная `load` вообще, если это какой-то флаг о процессе, обычно пишут `isLoading`, `isFetching`  и тд

2024-08-07 10:08 UTC, myaak commented on src/components/Comments/Comments.styled.ts
> +export const StyledCommentWrapper = styled(Button)``;
Пустой стайлед? Можно использовать проосто кнопку

2024-08-07 10:08 UTC, myaak commented on src/components/Comments/Comments.tsx
> +          dangerouslySetInnerHTML={{ __html: isCommentRemoved ? 'комментарий удален' : comment.content }}
Вообще в случае ХК можно и так, но если бы ты поддерживал отправку на свой бек, то уже нужно понимать что тут можно выстрелить себе в ногу

2024-08-07 10:08 UTC, myaak commented on src/components/Header/Header.tsx
> +            <h1>HACKER NEWS</h1>
Обычно в таких случаях полагаются на css стили

2024-08-07 10:08 UTC, myaak commented on src/components/Loading/Loading.tsx
> +const Loading = ({ count }: LoadingProps) => {
Компонент назыается "Загрузка". Ну может и норм. Но суть в том что у тебя `SkeletonList` или `SkeletonLoader`.

К тому же если ты не прокинул count можно дать ему базовое значение 1 или что хочешь, чтобы не писать много где `count={1}`

2024-08-07 10:08 UTC, myaak commented on src/components/News/News.styled.ts
> +import { Box } from '@mui/material';
Импорт из того же места дублируется

2024-08-07 10:08 UTC, myaak commented on src/components/News/News.tsx
> +const News = ({ id, title, time, time_ago, user, points }: NewsProps) => {
Не люблю такие вещи разбивать сильно, кинь просто целый объект и деструктурируй внутри уже

2024-08-07 10:08 UTC, myaak commented on src/main.tsx
> +    </BrowserRouter>
Я бы наверное тут не оборачивал, а сделал бы какой-то компонент с обертками. Не думал что App еще кто-то оборачивает.

Вкусовщина, наверное

2024-08-07 10:08 UTC, myaak commented on src/pages/Home/Home.tsx
> +      <NewsList>{loading ? <Loading count={10} /> : news.map((item) => <News key={item.id} {...item} />)}</NewsList>
Кажется не поправил

2024-08-07 10:08 UTC, myaak commented on src/pages/NewsDetail/NewsDetail.tsx
> +  if (loading) return <Loading count={1} />;
Как-будто можно лоадер поставить снизу по условию. + то что уже зарендерено не перерендерится.

Если это первая загрузка то `[].map`

2024-08-07 10:08 UTC, myaak commented on src/pages/NewsDetail/NewsDetail.tsx
> +    fetchNewsDetail(Number(id), true);
а если тут `NaN`

2024-08-07 10:08 UTC, myaak commented on src/components/UpdateButton/UpdateButton.tsx
> +  };
Ты можешь функцию прям по условию в `onClick` через тернарник кидать

2024-08-09 08:18 UTC, u1timaD commented on src/components/UpdateButton/UpdateButton.tsx
> +  };
Да, могу, но я вынес для лучшей читаемости

2024-08-09 08:20 UTC, u1timaD commented on src/main.tsx
> +    </BrowserRouter>
Проблем с происзводительностью быть не должно, поэтому можно обернуть, а можно и отсавить мне кажется

2024-08-12 08:45 UTC, IvanKoigerov commented on src/Store/news.ts
> +  ],
я уже писал, что тебе нет смысла хранить эту информацию тут

2024-08-12 08:45 UTC, IvanKoigerov commented on src/Store/news.ts
> +      if (!isEqual(news, allNews)) {
isEqual медленный, используй лучше https://www.npmjs.com/package/fast-deep-equal

2024-08-12 08:45 UTC, IvanKoigerov commented on src/Store/newsDetail.ts
> +        set({ loading: true });
@u1timaD

2024-08-12 08:45 UTC, IvanKoigerov commented on src/Store/newsDetail.ts
> +  fetchNewsDetail: async (id, load) => {
@u1timaD

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/Comments/Comments.styled.ts
> +export const StyledCommentWrapper = styled(Button)``;
@u1timaD

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/Comments/Comments.tsx
> +      {comment.comments && <Collapse in={open}>{comment.comments.map((child) => renderComment(child))}</Collapse>}
в несколько строчек напиши, так читать это очень неудобно и неприятно

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/Header/Header.styled.ts
> +  flex-direction: row;
row дефолтное значение

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/Header/Header.tsx
> +            <h1>HACKER NEWS</h1>
делаем @u1timaD

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/Loading/Loading.tsx
> +const Loading = ({ count }: LoadingProps) => {
Полностью согласен @u1timaD

2024-08-12 08:45 UTC, IvanKoigerov commented on src/components/News/News.tsx
> +const News = ({ id, title, time, time_ago, user, points }: NewsProps) => {
@myaak мне кажется так лучше)

2024-08-12 08:45 UTC, IvanKoigerov commented on src/pages/NewsDetail/NewsDetail.styled.ts
> +`;
Не делаем вложенных стилей, стилизируем все отдельно

2024-08-14 05:23 UTC, u1timaD commented on src/components/Comments/Comments.tsx
> +          dangerouslySetInnerHTML={{ __html: isCommentRemoved ? 'комментарий удален' : comment.content }}
да, я понимаю, что это не безопасно

2024-08-14 06:26 UTC, u1timaD commented on src/pages/Home/Home.tsx
> +      <NewsList>{loading ? <Loading count={10} /> : news.map((item) => <News key={item.id} {...item} />)}</NewsList>
у меня идёт проверка в сторе на загрузку, если первый раз, то загрузка происходит, если поледующие и данные не изменились, то загрузки нет

2024-08-14 07:40 UTC, u1timaD commented on src/Store/newsDetail.ts
> +        set({ loading: true });
Да, пропустил этот момент, поправил, должно работать. По логике, если у нас ренедриться первый раз, то loading переключается на true, дальше если новые данные и старые данные одинаковые, то loading остаётся false

2024-08-15 22:34 UTC, IvanKoigerov commented on src/components/Comments/Comments.tsx
> +  );
не не не, зачем ты держишь это в отдельной функции, при каждом рендере новая ссылки все дела, да и в принципе подход не очень, делай все в return
в принципе в реакте избегай таких тем, не выноси все в отдельную функцию, если хочешь можешь вынести все в отдельный компонент, но не в функцию и точно не в теле компонента

Также реакт вызов этой функции не считает компонентом, что тоже усложнает его работу с рендерами

2024-08-15 22:34 UTC, IvanKoigerov commented on src/components/Comments/Comments.tsx
> +};
не делаем в одном файле несколько компонентов, це плохо
Когда ты открываешь файл, то ждешь увидеть именно один компонент тут 

ну и нейминг 
CommentsList лучше всего тут подошел бы 
Comment либо просто либо CommentItem

2024-08-15 22:34 UTC, IvanKoigerov commented on src/components/SkeletonLoader/SkeletonLoader.tsx
> +export default SkeletonLoader;
Надо бы обозначить в названии как-то, что это именно несколько скелетонов, а не один

2024-08-15 22:34 UTC, IvanKoigerov commented on src/main.tsx
> +    </BrowserRouter>
Никогда не трогаем файл main, тут должен быть только app
Уже вроде писал где-то

2024-08-20 14:53 UTC, merged